version: '2'
services: 

  proxy: 
    build: proxy
    ports:
      - "80:3000"
    links: 
      - portal
      - campaign
      - sale
      - search

  portal: 
    build: portal

  sale:
    build: sale

  search: 
    build: search

  campaign:
    build: campaign
  
  recommendations:
    build: recommendations